#' Plot (S)MA using ggplot2
#'
#' @param obj object with class sma
#' @param ... arguments passed to geom_line()
#'
#' @return ggplot2 obj
#' @export
#'
#' 
ggplot.sma <- function(obj, ...){
  pdat <- make_plot_data(obj)
  
  if(obj$log == "")
  p <- ggplot_none(obj, pdat, ...)
  else(
  p <- switch(obj$log,
              "x" = ggplot_x(obj, pdat, ...),
              "y" = ggplot_y(obj, pdat, ...),
              "xy" = ggplot_xy(obj, pdat, ...))
  )
  p
}

#' Make ggplot with untransformed data
#' @param obj object with class sma
#' @param pdat plotting data generated by make_plot_data
#' @param ... arguments passed to ggplot and geom_line
#' @importFrom ggplot2 ggplot aes_string geom_point geom_line xlab ylab theme_bw scale_x_log10 scale_y_log10

ggplot_none <- function(obj, pdat, ...){
  if(any(obj$groups == "all"))
  p <- ggplot(data = pdat, aes_string(x = 'X', y = 'line_Y'), ...) 
  
  if(length(obj$groups) > 1)
  p <- ggplot(data = pdat, aes_string(x = 'X', y = 'line_Y', group = 'group', colour = 'group'), ...)
  
  # Construct rest of plot
  p +
    geom_point(aes_string(x = 'X', y = 'Y', group = 'group', colour = 'group'), shape = 21, size = 2) + 
    geom_line(...) + 
    ylab(label = obj$variables[1]) +
    xlab(label = obj$variables[2]) +
    theme_bw()
}

#' Make ggplot with transformed x axes only
#' @inheritParams ggplot_none

ggplot_x <- function(obj, pdat, ...){
  if(any(obj$groups == "all"))
    p <- ggplot(data = pdat, aes_string(x = 'X_raw', y = 'line_Y'), ...) 
    
  if(length(obj$groups) > 1)
   p <- ggplot(data = pdat, aes_string(x = 'X_raw', y = 'line_Y', group = 'group', colour = 'group'), ...) 
    
  # Construct rest of plot
    p + 
    geom_point(aes_string(x = 'X_raw', y = 'Y', group = 'group', colour = 'group'), shape = 21, size = 2) +
    geom_line(...) + 
    scale_x_log10() +
    ylab(label = obj$variables[1]) +
    xlab(label = obj$variables[2]) +
    theme_bw()
}

#' Make ggplot with transformed y axes only
#' @inheritParams ggplot_none

ggplot_y <- function(obj, pdat, ...){
  if(any(obj$groups == "all"))
    p <- ggplot(data = pdat, aes_string(x = 'X', y = 'line_Y'), ...) 
  
  if(length(obj$groups) > 1)
    p <- ggplot(data = pdat, aes_string(x = 'X', y = 'line_Y', group = 'group', colour = 'group'), ...)
  
  # Construct rest of plot
  p +
    geom_point(aes_string(x = 'X', y = 'Y_raw', group = 'group', colour = 'group'), shape = 21, size = 2) + 
    geom_line(...) + 
    scale_y_log10() + 
    ylab(label = obj$variables[1]) +
    xlab(label = obj$variables[2]) +
    theme_bw()
}

#' Make ggplot with transformed x and y axes 
#' @inheritParams ggplot_none

ggplot_xy <- function(obj, pdat, ...){
  if(any(obj$groups == "all"))
    p <- ggplot(data = pdat, aes_string(x = 'X', y = 'line_Y'), ...) 
  
  if(length(obj$groups) > 1)
    p <- ggplot(data = pdat, aes_string(x = 'X_raw', y = 'line_Y', group = 'group', colour = 'group'), ...)
  
  # Construct rest of plot
  p +
    geom_point(aes_string(x = 'X_raw', y = 'Y_raw', group = 'group', colour = 'group'), shape = 21, size = 2) + 
    geom_line(...) + 
    scale_x_log10() +
    scale_y_log10() + 
    ylab(label = obj$variables[1]) +
    xlab(label = obj$variables[2]) +
    theme_bw()
}

#' Make plotting data from sma obj 
#'
#' @param obj object with class sma

make_plot_data <- function(obj){
  
  if(obj$log == "") 
  pdat  <- make_data_raw(obj) 
  
  else(
    pdat <- switch(obj$log,
                "x" = make_data_x(obj),
                "y" = make_data_y(obj),
                "xy" = make_data_xy(obj)
                )
  )
  pdat
}
   
#' Reformat data for plotting on untransformed data
#'
#' @param obj ma or sma obj
#' @importFrom dplyr group_by mutate
#' @importFrom rlang .data
#' @return tibble of plotting data
#' @keywords internal

make_data_raw <- function(obj){
  if(any(obj$groups == "all")){
    # No groups
    pdat <- dplyr::tibble(X = obj$data[,2],
                          Y = obj$data[,1],
                          line_Y = summary(obj)$Int + .data$X*summary(obj)$Slope) #a + x*B
  }else{
    groups <- levels(obj$data[,3])
    
    pdat <- dplyr::tibble(X = obj$data[,2],
                          Y = obj$data[,1],
                          group = obj$data[,3])
    
    for(i in 1:length(groups)){
      pdat[pdat$group == groups[i],"a"] <- get_coef(obj = obj, 
                                                    group_level = groups[i],
                                                    coef_type = "a")
      
      pdat[pdat$group == groups[i],"B"] <- get_coef(obj = obj, 
                                                    group_level = groups[i],
                                                    coef_type = "B")
      
      pdat <- pdat |> mutate(line_Y = .data$a + .data$X*.data$B)
    }
  }
  pdat
}

 #' Reformat data for plotting on log transformed x
 #'
 #' @inheritParams make_data_raw

 make_data_x <- function(obj){
   if(any(obj$groups == "all")){
    pdat <- dplyr::tibble(X = obj$data[,2], #On log scale
                   Y = obj$data[,1],
                   X_raw = 10^.data$X,
                   line_Y = summary(obj)$Int + summary(obj)$Slope*log10(.data$X_raw) #a+B*log10(x) 
     )
   }else{
     pdat <- dplyr::tibble(X = obj$data[,2],
                           Y = obj$data[,1],
                           X_raw = 10^.data$X,
                           group = obj$data[,3])
     
     groups <- levels(obj$data[,3])
     
     for(i in 1:length(groups)){
       pdat[pdat$group == groups[i],"a"] <- get_coef(obj = obj, 
                                                     group_level = groups[i],
                                                     coef_type = "a")
       
       pdat[pdat$group == groups[i],"B"] <- get_coef(obj = obj, 
                                                     group_level = groups[i],
                                                     coef_type = "B")
       
       pdat <- pdat |> mutate(line_Y = .data$a + .data$B*log10(.data$X_raw))
     }
   }
   pdat
 }
 

 #' Reformat data for plotting on log transformed y
 #'
 #' @inheritParams make_data_raw
 
 make_data_y <- function(obj){
   if(any(obj$groups == "all")){
     pdat <-  dplyr::tibble(X = obj$data[,2],
                            Y = obj$data[,1], #On log scale
                            Y_raw = 10^.data$Y,
                            line_Y = 10^(summary(obj)$Int + summary(obj)$Slope*.data$X) # 10^(a+x*B)
     )
   }else{
     pdat <- dplyr::tibble(X = obj$data[,2],
                           Y = obj$data[,1],
                           Y_raw = 10^.data$Y,
                           group = obj$data[,3])
     
     groups <- levels(obj$data[,3])
     for(i in 1:length(groups)){
       pdat[pdat$group == groups[i],"a"] <- get_coef(obj = obj, 
                                                     group_level = groups[i],
                                                     coef_type = "a")
       
       pdat[pdat$group == groups[i],"B"] <- get_coef(obj = obj, 
                                                     group_level = groups[i],
                                                     coef_type = "B")
       
       pdat <- pdat |> mutate(line_Y = 10^(.data$a + .data$B*.data$X)) # 10^(a+x*B)
     }
   }
   pdat
 }

 #' Reformat data for plotting on log transformed x and y
 #'
 #' @inheritParams make_data_raw
 
 make_data_xy <- function(obj){
   if(any(obj$groups == "all")){
   pdat <- dplyr::tibble(X = obj$data[,2], #On log scale
                 Y = obj$data[,1], #On log scale
                 X_raw = 10^.data$X,
                 Y_raw = 10^.data$Y,
                 line_Y = 10^summary(obj)$Int * .data$X_raw^summary(obj)$Slope # 10^a*x^B
                 )
   }else{
     pdat <- dplyr::tibble(X = obj$data[,2], #On log scale
                           Y = obj$data[,1], #On log scale
                           X_raw = 10^.data$X,
                           Y_raw = 10^.data$Y,
                           group = obj$data[,3])
     
     groups <- levels(obj$data[,3])
     for(i in 1:length(groups)){
       pdat[pdat$group == groups[i],"a"] <- get_coef(obj = obj, 
                                                     group_level = groups[i],
                                                     coef_type = "a")
       
       pdat[pdat$group == groups[i],"B"] <- get_coef(obj = obj, 
                                                     group_level = groups[i],
                                                     coef_type = "B")
       
       pdat <- pdat |> mutate(line_Y = 10^.data$a*.data$X_raw^.data$B) # 10^a*x^B
     }
   }
   pdat  
 }


 #' Extract coefficients for each level of group
 #'
 #' @param obj object with sma class 
 #' @param group_level character string of group level
 #' @param coef_type type of coefficient you want a for intercept B for slope
 #' @importFrom dplyr filter pull
 #' @importFrom rlang .data
 
 get_coef <- function(obj, group_level, coef_type){
   
   groupsum <- obj$groupsummary
   
   if(coef_type == "a"){
     a <- groupsum |> filter(.data$group == group_level) |>  pull("Int")
     return(a)
   } 
   
   if(coef_type == "B"){
     B <- groupsum |> filter(.data$group == group_level) |>  pull("Slope")
     return(B)
   }
 }
 